version: '3.7'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - app_1
      - app_2
  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  app_1:
    build: ./app_1
    environment:
      RAILS_ENV: development
    volumes:
      - ./app_1:/app_home
    depends_on:
      - postgres
    stdin_open: true
    tty: true
  app_2:
    build: ./app_2
    environment:
      RAILS_ENV: development
    volumes:
      - ./app_2:/app_home
    depends_on:
      - postgres
    stdin_open: true
    tty: true
volumes:
  postgres: {}
