default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  host: postgres
  database: app_1_development

test:
  <<: *default
  host: postgres
  database: app_1_test

production:
  <<: *default
  database: app_1_production
  username: app_1
  password: <%= ENV["SUM_DATABASE_PASSWORD"] %>
