default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  host: postgres
  database: app_2_development

test:
  <<: *default
  host: postgres
  database: app_2_test

production:
  <<: *default
  database: app_2_production
  username: app_2
  password: <%= ENV["SUM_DATABASE_PASSWORD"] %>
